{{- if and .Values.operator.enabled .Values.operator.admissionWebhooks.deployment.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.operator.admissionWebhooks.deployment.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "prometheus-operator.admissionWebhooks.serviceAccountName" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels:
    app: {{ template "prometheus-operator.name" . }}-operator
    {{- include "prometheus-operator.admission-webhooks.labels" . | indent 4 }}
  {{- with .Values.operator.admissionWebhooks.deployment.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "prometheus-operator.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}
