{{- if and .Values.operator.enabled .Values.operator.admissionWebhooks.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-webhook
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels:
    app: {{ template "prometheus-operator.name" . }}-operator-webhook
    {{- include "prometheus-operator.admission-webhooks.labels" . | nindent 4 }}
{{- if .Values.operator.admissionWebhooks.deployment.service.labels }}
{{ toYaml .Values.operator.admissionWebhooks.deployment.service.labels | indent 4 }}
{{- end }}
{{- if .Values.operator.admissionWebhooks.deployment.service.annotations }}
  annotations:
{{ toYaml .Values.operator.admissionWebhooks.deployment.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.operator.admissionWebhooks.deployment.service.clusterIP }}
  clusterIP: {{ .Values.operator.admissionWebhooks.deployment.service.clusterIP }}
{{- end }}
{{- if .Values.operator.admissionWebhooks.deployment.service.ipDualStack.enabled }}
  ipFamilies: {{ toYaml .Values.operator.admissionWebhooks.deployment.service.ipDualStack.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.operator.admissionWebhooks.deployment.service.ipDualStack.ipFamilyPolicy }}
{{- end }}
{{- if .Values.operator.admissionWebhooks.deployment.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.operator.admissionWebhooks.deployment.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.operator.admissionWebhooks.deployment.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.operator.admissionWebhooks.deployment.service.loadBalancerIP }}
{{- end }}
{{- if .Values.operator.admissionWebhooks.deployment.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.operator.admissionWebhooks.deployment.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if ne .Values.operator.admissionWebhooks.deployment.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.operator.admissionWebhooks.deployment.service.externalTrafficPolicy }}
{{- end }}
  ports:
  {{- if not .Values.operator.admissionWebhooks.deployment.tls.enabled }}
  - name: http
    {{- if eq .Values.operator.admissionWebhooks.deployment.service.type "NodePort" }}
    nodePort: {{ .Values.operator.admissionWebhooks.deployment.service.nodePort }}
    {{- end }}
    port: 8080
    targetPort: http
  {{- end }}
  {{- if .Values.operator.admissionWebhooks.deployment.tls.enabled }}
  - name: https
    {{- if eq .Values.operator.admissionWebhooks.deployment.service.type "NodePort"}}
    nodePort: {{ .Values.operator.admissionWebhooks.deployment.service.nodePortTls }}
    {{- end }}
    port: 443
    targetPort: https
  {{- end }}
  selector:
    app: {{ template "prometheus-operator.name" . }}-operator-webhook
    release: {{ $.Release.Name | quote }}
  type: "{{ .Values.operator.admissionWebhooks.deployment.service.type }}"
{{- end }}
