{{- if .Values.crdUpgradeJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheus-operator.crdUpgradeJob.name" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "prometheus-operator.crdUpgradeJob.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ template "prometheus-operator.namespace" . }}
    name: {{ template "prometheus-operator.crdUpgradeJob.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "prometheus-operator.crdUpgradeJob.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
