{{- if and .Values.crdUpgradeJob.enabled .Values.crdUpgradeJob.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.crdUpgradeJob.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "prometheus-operator.crdUpgradeJob.serviceAccountName" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.crdUpgradeJob.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "prometheus-operator.crdUpgradeJob.labels" . | nindent 4 }}
    {{- with .Values.crdUpgradeJob.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
