{{- if and .Values.operator.enabled .Values.global.rbac.create .Values.global.rbac.pspEnabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-psp
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-operator.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.serviceAccountName" . }}
    namespace: {{ template "prometheus-operator.namespace" . }}
{{- end }}
{{- end }}
