{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.serviceAccountName" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.operator.serviceAccount.automountServiceAccountToken }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "prometheus-operator.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}
