{{- if and .Values.operator.enabled .Values.operator.admissionWebhooks.enabled .Values.operator.admissionWebhooks.patch.enabled .Values.global.rbac.create (not .Values.operator.admissionWebhooks.certManager.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "prometheus-operator.fullname" . }}-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "prometheus-operator.name" $ }}-admission
    {{- include "prometheus-operator.admission-webhooks.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-operator.fullname" . }}-admission
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-operator.fullname" . }}-admission
    namespace: {{ template "prometheus-operator.namespace" . }}
{{- end }}
