{{- if and .Values.operator.enabled .Values.operator.admissionWebhooks.enabled .Values.operator.admissionWebhooks.patch.enabled (not .Values.operator.admissionWebhooks.certManager.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "prometheus-operator.fullname" . }}-admission-patch
  namespace: {{ template "prometheus-operator.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- with .Values.operator.admissionWebhooks.patch.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "prometheus-operator.name" $ }}-admission-patch
    {{- include "prometheus-operator.admission-webhooks.labels" $ | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.operator.admissionWebhooks.patch.ttlSecondsAfterFinished }}
  template:
    metadata:
      name:  {{ template "prometheus-operator.fullname" . }}-admission-patch
{{- with .Values.operator.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app: {{ template "prometheus-operator.name" $ }}-admission-patch
        {{- include "prometheus-operator.admission-webhooks.labels" $ | nindent 8 }}
    spec:
      {{- if .Values.operator.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.operator.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "prometheus-operator.imagePullSecrets" . | indent 8 }}
      {{- end }}
      containers:
        - name: patch
          {{- $registry := .Values.global.imageRegistry | default .Values.operator.admissionWebhooks.patch.image.registry -}}
          {{- if .Values.operator.admissionWebhooks.patch.image.sha }}
          image: {{ $registry }}/{{ .Values.operator.admissionWebhooks.patch.image.repository }}:{{ .Values.operator.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.operator.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ $registry }}/{{ .Values.operator.admissionWebhooks.patch.image.repository }}:{{ .Values.operator.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.operator.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ template "prometheus-operator.fullname" . }}-admission
            - --namespace={{ template "prometheus-operator.namespace" . }}
            - --secret-name={{ template "prometheus-operator.fullname" . }}-admission
            - --patch-failure-policy={{ .Values.operator.admissionWebhooks.failurePolicy }}
          {{- with .Values.operator.admissionWebhooks.patchWebhookJob }}
          securityContext:
          {{ toYaml .securityContext | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.operator.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "prometheus-operator.fullname" . }}-admission
      {{- with .Values.operator.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.operator.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.operator.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- if .Values.operator.admissionWebhooks.patch.securityContext }}
      securityContext:
{{ toYaml .Values.operator.admissionWebhooks.patch.securityContext | indent 8 }}
{{- end }}
{{- end }}
