{{- if and .Values.operator.enabled .Values.operator.admissionWebhooks.enabled .Values.operator.admissionWebhooks.patch.enabled .Values.operator.admissionWebhooks.patch.serviceAccount.create (not .Values.operator.admissionWebhooks.certManager.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "prometheus-operator.fullname" . }}-admission
  namespace: {{ template "prometheus-operator.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "prometheus-operator.name" $ }}-admission
    {{- include "prometheus-operator.admission-webhooks.labels" $ | nindent 4 }}
  {{- with .Values.operator.admissionWebhooks.patch.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.operator.admissionWebhooks.patch.serviceAccount.automountServiceAccountToken }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "prometheus-operator.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}
