name: Release

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Helm chart
        env:
          VERSION: ${{ github.event.release.name }}
        run: |
          helm package . --version $VERSION --dependency-update
          helm push prometheus-operator-${VERSION}.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
